services:
  db:
    image: postgres:15-alpine
    container_name: dashboard-company-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dashboard-company
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - dashboard-company-network
    volumes:
      - postgres-data:/var/lib/postgres/data

  pg-admin:
    image: dpage/pgadmin4
    container_name: dashboard-company-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: flaviojunior.work@gmail.com
      PGADMIN_DEFAULT_USER: renato
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    expose:
        - 5050
    depends_on:
      - db
    networks:
      - dashboard-company-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

  dashboard-company:
    image: flaviojunior/dashboard-company
    container_name: dashboard-company
    restart: always
    build: ./back-end
    working_dir: /back-end
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dashboard-company?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - 8001:8001
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - dashboard-company-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  dashboard-company-network:
    driver: bridge
