server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST_PROD}:${DATABASE_PORT_PROD}/${DATABASE_NAME_PROD}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DATABASE_PASSWORD_PROD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true