services:
  db:
    image: postgres:17
    container_name: dashboard-company-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME_TEST}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_TEST}
      POSTGRES_DB: ${DATABASE_NAME_TEST}
    ports:
      - ${DATABASE_PORT_TEST}:${DATABASE_PORT_TEST}
    expose:
      - ${DATABASE_PORT_TEST}
    networks:
      - dashboard-company-network
    volumes:
      - postgres-data:/var/lib/postgres/data

  pg-admin:
    image: dpage/pgadmin4
    container_name: dashboard-company-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL_TEST}
      PGADMIN_DEFAULT_USER: ${PGADMIN_DEFAULT_USER_TEST}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD_TEST}
    ports:
      - ${PGADMIN_PORT_TEST}:${PGADMIN_DEFAULT_PORT_TEST}
    expose:
        - ${PGADMIN_PORT_TEST}
    depends_on:
      - db
    networks:
      - dashboard-company-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

  dashboard-company:
    image: flaviojunior/dashboard-company
    container_name: dashboard-company
    restart: always
    build: ./back-end
    working_dir: /back-end
    environment:
      SECRET-KEY: ${SECRET-KEY}
      SERVER_PORT_TEST: ${SERVER_PORT_TEST}
      DATABASE_URL_TEST: ${DATABASE_URL_TEST}
      DATABASE_PORT_TEST: ${DATABASE_PORT_TEST}
      DATABASE_NAME_TEST: ${DATABASE_NAME_TEST}
      DATABASE_USERNAME_TEST: ${DATABASE_USERNAME_TEST}
      DATABASE_PASSWORD_TEST: ${DATABASE_PASSWORD_TEST}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DATABASE_PORT_TEST}/${DATABASE_NAME_TEST}?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME_TEST}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD_TEST}
    ports:
      - ${SERVER_PORT_TEST}:${SERVER_PORT_TEST}
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - dashboard-company-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  dashboard-company-network:
    driver: bridge
