spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dashboard-company
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true