spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dashboard-company?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true